# Generated by Django 5.2.7 on 2025-10-28 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('edad', models.PositiveSmallIntegerField(help_text='Edad en años (14 a 120).', validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(120)])),
                ('telefono', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido (solo dígitos, +, -, espacios y paréntesis).', regex='^[0-9+\\-\\s()]{6,20}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('pdf_lua', models.FileField(upload_to='pdfs/')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('entregado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='lua.alumno')),
            ],
            options={
                'verbose_name': 'Requisito del alumno',
                'verbose_name_plural': 'Requisitos del alumno',
                'ordering': ['nombre'],
                'unique_together': {('alumno', 'nombre')},
            },
        ),
    ]
